name: Test & Lint

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install
        run: pnpm install
      - name: Typecheck
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
